#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB17327D40171DF30 (jannis@leidel.info)
#
Name     : django-discover-runner
Version  : 1.0
Release  : 19
URL      : https://pypi.python.org/packages/source/d/django-discover-runner/django-discover-runner-1.0.tar.gz
Source0  : https://pypi.python.org/packages/source/d/django-discover-runner/django-discover-runner-1.0.tar.gz
Source99 : https://pypi.python.org/packages/source/d/django-discover-runner/django-discover-runner-1.0.tar.gz.asc
Summary  : A Django test runner based on unittest2's test discovery.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: django-discover-runner-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
django-discover-runner
======================
.. note::
This runner has been added to Django 1.6 as the default test runner.
If you use Django 1.6 or above you don't need this app.

%package python
Summary: python components for the django-discover-runner package.
Group: Default

%description python
python components for the django-discover-runner package.


%prep
%setup -q -n django-discover-runner-1.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484543009
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484543009
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
